# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a546f477abf6088d7ee829fb2260d22683ff80ec5ed3ba20182ec2bebabe91299dfaa6035ec774d0e9070f1b572813949478457c69d041b6c6a2e03b916b22d3

test:
  secret_key_base: 39c10f0290e0f9c8e2a898294123a2827fcc7a44d3c98c518bd1c25448d4dc2483e7ad82cd3b80ffe32b6e64fe261c007d23078a8d5333537f8ef7bccf24fc67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
